/**
 * Generated by typasaur
 *
 *                    __
 *                   / _)
 *          .-^^^-/ /
 *      __/       /
 *     <__.|_|-|_|
 *
 * JSON to TypeScript Model CLI
 */

export type Addresse = {
  city: string;
  country: string;
  line1: string;
  line2: any;
  postalCode: string;
  type: string;
};

export type Customer = {
  addresses: Addresse[];
  email: string;
  firstName: string;
  id: number;
  lastName: string;
};

export type Item = {
  name: string;
  price: number;
  quantity: number;
  sku: string;
  variants: any[];
};

export type Payment = {
  amount: number;
  currency: string;
  method: string;
  paidAt: string | Date;
  transactionId: string;
};

export type Shipping = {
  carrier: string;
  estimatedDelivery: string | Date;
  trackingNumber: string;
};

export type Family = {
  customer: Customer;
  items: Item[];
  notes: any;
  orderId: string;
  payment: Payment;
  shipping: Shipping;
  status: string;
  tags: ("ecommerce" | "priority" | "gift")[];
};
